name: "💡 CWE Submission"
description: "The name should focuses on the weakness/mistake - not the attack. Minimize use of ambiguous words to keep the name short.\n"
title: "💡 [NEW Submission] - <name>"
labels: [
  "01-Received"
]
body:
  - type: textarea
    id: cwe_summary
    attributes:
      label: "Summary"
      description: "The summary consists of only one or two sentences that describe the weakness itself, i.e. the mistake that is made.\n
      Often, the summary will describe what the developer/designer is attempting to do.\n
      Critical parts of the summary include:\n
      1. the intended behavior of the code\n
      2. the mistake (i.e. weakness)\n
      3. the affected resource (if relevant)\n
      4. the affected technology (if relevant)\n\n
      
      Each summary part is only expressed with individual words or brief phrases; the extended description can be more\n
      comprehensive in its explanation.\n\n
      Use of CWE-specific vocabulary is preferred but not required.\n\n"
      
      placeholder: "Proposed CWE Summary"
    validations:
      required: true
