name: "💡 CWE Submission"
description: Submit a proposal for a new weakness within CWE.
title: "💡 [NEW Submission] - :{{ cwe_name }}
labels: [
  "01-Received"
]
body:
  - type: input
    id: cwe_name
    attributes:
      label: "Name"
      description: "Ideally, the name focuses on the weakness/mistake - not the attack. Minimize use of ambiguous words to keep the name short.\n
                    Where feasible, use terminology as defined in the CWE glossary and/or vulnerability theory documents.\n
                    The name should include:\n 
                    1. the intended behavior of the code\n 
                    2. the mistake (i.e. weakness)\n
                    3. the affected resource (if relevant)\n
                    4. the affected technology (if relevant). Use of CWE-specific vocabulary is preferred but not required.\n"
      placeholder: "Proposed CWE title"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "The summary consists of only one or two sentences that describe the weakness itself, i.e. the mistake that is made.\n
                    Often, the summary will describe what the developer/designer is attempting to do.\n
                    Critical parts of the summary include:\n
                    1. the intended behavior of the code\n
                    2. the mistake (i.e. weakness)\n
                    3. the affected resource (if relevant)\n
                    4. the affected technology (if relevant)\n\n
                    Each summary part is only expressed with individual words or brief phrases; the extended description can be more\n
                    comprehensive in its explanation.\n\n
                    Use of CWE-specific vocabulary is preferred but not required.\n\n
                    
                    The summary (and name) should avoid focusing on:\n
                    1. the attack\n
                    2. the absence of a mitigation\n
                    3. the technical impact.\n\n
                    
                    If a summary has a strong reliance on this information, this may be an indicator that the entry is not weakness-focused."
      placeholder: "Proposed CWE Summary"
    validations:
      required: true
