name: "💡 CWE Submission"
description: Submit a proposal for a new weakness within CWE.
title: "💡 [NEW Submission] - <title>"
labels: [
  "question"
]
body:
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Ideally, the name focuses on the weakness/mistake - not the attack. Minimize use of ambiguous words to keep the name short.\n
                    Where feasible, use terminology as defined in the CWE glossary and/or vulnerability theory documents. The name should include:\n 
                    1. the intended behavior of the code\n 
                    2. the mistake (i.e. weakness)\n
                    3. the affected resource (if relevant)\n
                    4. the affected technology (if relevant). Use of CWE-specific vocabulary is preferred but not required.\n"
      placeholder: "Proposed CWE title"
    validations:
      required: false
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Pull request used
      placeholder: "#Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request ?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
